class Constants {
  Constants._();

  static const ENV_BASE_URL_KEY = 'BASE_URL';

  static const ENV_REST_CLIENT_CONNECT_TIMEOUT_KEY =
      'REST_CLIENT_CONNECT_TIMEOUT';

  static const ENV_REST_CLIENT_RECEIVE_TIMEOUT_KEY =
      'REST_CLIENT_RECEIVE_TIMEOUT';

  static const LOCAL_STORAGE_ACCESS_TOKEN_KEY =
      '/LOCAL_STORAGE_ACCESS_TOKEN_KEY/';
}
